# Generated by Django 4.2.1 on 2023-05-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AparatoE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Ingrese la descripcion', max_length=100)),
            ],
            options={
                'verbose_name': 'AparatoElectronico',
                'verbose_name_plural': 'AparatosElectronicos',
            },
        ),
    ]
