# Generated by Django 4.2.1 on 2023-05-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aparato_Electronico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoElectrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristicas', models.CharField(help_text='Ingrese las caracteristicas', max_length=100)),
                ('nombre', models.CharField(help_text='Ingrese nombre', max_length=36)),
                ('aparatoE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aparato_Electronico.aparatoe')),
            ],
            options={
                'verbose_name': 'Tipo Electrodomestico',
                'verbose_name_plural': 'Tipo Electrodomestico',
            },
        ),
    ]
