# Generated by Django 4.2.1 on 2023-05-17 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Componente_Piezas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFabricante', models.CharField(help_text='Ingrese nombre del fabricante', max_length=100)),
                ('domicilio', models.CharField(help_text='Ingrese domicilio social', max_length=36)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Componente_Piezas.componente')),
            ],
            options={
                'verbose_name': 'Fabicrante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
    ]
